import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "black", 
        justifyContent: "flex-end", 
        alignItems: "center"
    },
    boxColumn: {
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        position: "absolute",
        top: "43%",
        width: "90%",
        height: "41%",
    },
    boxRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        width: "100%",
    },
    textContainer: {
        alignItems: "center",
        justifyContent: "center",
    },
    vector: {
        right: 0,
    },
    vectorMirror: {
        left: 0,
        transform: [{scaleX: -1}],
    },
    text: { 
        fontSize: 24, 
        color: "white", 
        textAlign: 'center',
        fontFamily: 'SF-Pro',
        lineHeight: 29,
        transform: [{ scaleX: 1.25 }], 
    },
    textBold: { 
        fontSize: 27, 
        fontWeight: "bold",
        color: "white", 
        textAlign: 'center',
        fontFamily: 'SF-Pro',
        lineHeight: 32,
        transform: [{ scaleX: 1.3}], 
        letterSpacing: -1.5,
    },
    textLow: { 
        fontSize: 15, 
        color: "white", 
        textAlign: 'center',
        fontFamily: 'SF-Pro',
        lineHeight: 18,
        transform: [{ scaleX: 1.25 }], 
    },
    textLowWide: { 
        fontSize: 17, 
        color: "white", 
        textAlign: 'center',
        fontFamily: 'SF-Pro',
        lineHeight: 20,
        transform: [{ scaleX: 1.4 }], 
    },
    background: {
        width: "100%",
        height: "65%",
        justifyContent: "center",
        alignItems: "center",
        top: "5%",
        position: "absolute",
    },
    gradientBox: {
        position: "absolute",
        width: "100%",
        height: "75%",
        bottom: 0,
    },
    button: {
        backgroundColor: "white",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 50,
        alignItems: "center",
        justifyContent: "center",
        bottom: 30,
        width: "90%",
        height: 65,
    },
    buttonText: {
        color: "black",
        textAlign: 'center',
        fontSize: 25,
        fontWeight: "bold",
        lineHeight: 30,
        fontFamily: 'SF-Pro',
        transform: [{ scaleX: 1.1 }],
        letterSpacing: 0.5,
    },
}); 