import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    viewRowsBetweenAround: {
        flex: 1,
        justifyContent: "center",
        rowGap: "27%",
        alignItems: "center",
        alignSelf: "center",
        position: "absolute",
        width: "100%",
        height: "100%",
        paddingHorizontal: 17,
        paddingBottom: 50,
        backgroundColor: "black",
    },
    viewText: {
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        flexDirection: "row",
        flexWrap: "wrap",
    },
    textBoldLeft: { 
        fontSize: 34, 
        fontWeight: "bold",
        color: "white", 
        textAlign: 'left',
        fontFamily: 'SF-Pro',
        lineHeight: 41,
        width: "100%",
    },
    textBoldItalic: { 
        fontWeight: 700, 
        fontStyle: 'italic',
        transform: [{ scaleX: 1.1}],
        transformOrigin: 'left',
        color: "white",
        fontSize: 34, 
        fontFamily: 'SF-Pro',
        lineHeight: 41,
        marginRight: 15,
    },
    textRegular: { 
        fontSize: 17, 
        // fontWeight: "bold",
        color: "white", 
        textAlign: 'left',
        fontFamily: 'SF-Pro',
        lineHeight: 20,
        letterSpacing: -0.7,
    },
    buttonContainer: {
        width: "100%",
        alignItems: "center",
        bottom: "4%",
        position: "absolute",
    },
    progressBar: {
        width: "100%",
        height: 10,
        backgroundColor: "#191919",
        position: "absolute",
        top: 50,
        borderRadius: 5,
    },
    progressFill: {
        height: "100%",
        backgroundColor: "white",
        width: `${(1/12 * 100)}%`,
        borderRadius: 5,
    },
}); 